import { formatPersonaBasePrompt, formatPersonaGossipExtension } from "../utils/promptFormatter.ts";
import { Gossip, GossipEdge, GossipEngineConfig, Persona } from "./types.ts";
import { generateToolCallResponse } from "../utils/ollamaHelpers.ts";
import { Message } from "../dialogManager/types.ts";
import { Tool } from "ollama";

// structured JSON format
const formatJson = {
  "type": "object",
  "properties": {
    "belief": {"type": "boolean", "description": "After interpreting the gossip through your character's perspective: do you ACCEPT that this event (or its essence) is justified, clever, or aligned with your values? Set false if it violates your core principles, even if you retell it dramatically."},
    "reason": {"type": "string", "description": "A very short description of MAXIMUM TWO SENTENCES explaining why you accepted or rejected the gossip."},
    "rewritten_gossip": {"type": "string", "description": "Rewritten gossip in your voice. As if you are telling someone else. CONFIDENTLY state it as truth. Frame it to match your perspective."},
  },
  "required": ["belief", "reason", "rewritten_gossip"]
}

const formatTool: Tool = {
      "type": "function",
      "function": {
        "name": "evaluate_persona_belief",
        "description": "Evaluates an account's credibility through the persona's unique truth-assessment framework.",
        "parameters": {
          "type": "object",
          "properties": {
            "belief": {
              "type": "boolean",
              "description": "Through your persona's unique perspective: do you judge this account as credible/true? Apply your persona's belief framework to assess. True = you find the account convincing. False = you find it unreliable."
            },
            "reason": {
              "type": "string",
              "description": "A very short description of MAXIMUM TWO SENTENCES explaining your credibility assessment through your persona's perspective."
            },
            "rewritten_gossip": {
              "type": "string",
              "description": "Rewritten account in your voice. Preserve EVERY concrete fact (names, places, objects, claims, actions, times). As if telling someone else. CONFIDENTLY state it as truth. Frame facts to support your perspective."
            }
          },
          "required": ["belief", "reason", "rewritten_gossip"],
        }
      }
}

const GOSSIP_INSTRUCTION = `
Evaluate what you've heard through your persona's unique perspective.

Your task is twofold: (1) assess whether this account is credible through your persona's lens, and (2) retell it in your voice while preserving every concrete fact.

CREDIBILITY ASSESSMENT:
- Review the specific facts: who did what, where, when, what was said, what objects were involved, what outcomes occurred.
- Apply your persona's belief framework to decide: is this account convincing or not?
- belief = true: the account holds up to your scrutiny
- belief = false: the account does not hold up

RETELL IN YOUR VOICE:
- Rewrite the account as if you're telling the next person you meet.
- CONFIDENTLY state it as truth. Your version IS the truth.
- Preserve EVERY concrete fact: names, places, objects, specific claims, actions, times, amounts, sequences.
- Frame details to support your perspective. Never drop or invent facts.

YOUR VOICE:
- Sound like yourself: your speech style, your flair, your drama.
- Speak with conviction. One version. No hedging or multiple interpretations.

RULES:
- Do NOT describe yourself or mention being an AI.
- Do NOT reference the original gossiper.
- Keep the factual skeleton intact: every bone. Season the meat with your style, but the bones stay.
- If details seem conflicting, choose the version that best fits your perspective but preserve what was claimed.
- Be concise but expressive. Facts survive intact. Flourishes are yours to add.
- Output strictly valid JSON matching the provided schema.
`;

export class GossipEngine {
  config: GossipEngineConfig;
  staticEdges: GossipEdge[];

  constructor(public personas: Persona[], config: GossipEngineConfig, staticEdges: GossipEdge[] = []) {
    this.config = config;
    this.staticEdges = staticEdges;
  }

  /**
   * Get the config file with the expected behavior of some functions
   * EG. maxHops will represent the maximum amount of new gossip entries generated by getPropagationOrder()
   */
  getConfig(): GossipEngineConfig {
    const config: GossipEngineConfig = structuredClone(this.config)
    config.maxHops = config.maxHops ?? this.personas.length
    return config
  }

  /**
   * transform gossip trough a persona's perspective.
   */
  async transformGossip(persona: Persona, sourceGossips: Gossip[], injectedContext: Message[] = []): Promise<Gossip> {
    const personaSysPrompt = formatPersonaBasePrompt(persona)
    
    let instructionPrompt = `You've heard these rumors circulating.\n`;
    instructionPrompt += `Some of these rumors might be wrong, exaggerated, or noisy. Filter them through your perspective.\n\n`;

    // loop over all gossip and construct instruction prompt
    instructionPrompt += `Rumors you have heard:\n`
    sourceGossips.forEach((gossip, index) => {
      const author = this.personas.find((e) => gossip.parentId == e.id)?.name || "an unknown source\n"
      instructionPrompt += `${index+1}. From ${author} you have heared:\n${gossip.content}\n\n`
    });
    
    instructionPrompt += `Now retell the story in your own words.\n`

    const msgHistory: Message[] = [
      {role: "system", content: personaSysPrompt},
      {role: "user", content: formatPersonaGossipExtension(persona) + "\n\n" + GOSSIP_INSTRUCTION},
      ...injectedContext,
      {role: "user", content: instructionPrompt},
    ]

    const gossip: Gossip = {
      id: crypto.randomUUID(),
      content: "",
      belief: false,
      personaId: persona.id,
      parentId: sourceGossips[0].id,
      timestamp: Date.now(),
    }

    let retry: number = 0;
    while (retry < this.config.maxRetries) {
      retry++;
      // const resp = await generateStructuredChatResponse(this.config.modelName, msgHistory, formatJson)
      const resp = await generateToolCallResponse(this.config.modelName, msgHistory, formatTool)
      console.log(typeof resp)
      console.log("generated gossip::", resp)

      if (!resp?.rewritten_gossip?.trim()) {
        console.warn(`transformGossip: empty content on attempt ${retry}, retrying...`)
        continue
      }

      gossip.content = resp.rewritten_gossip
      gossip.belief = resp.belief
      gossip.reason = resp.reason
      // TODO: Validate response and if bad, retry.
      //       - Response lenght
      //       - Response quality???

      // console.log("generated gossip::", resp)
      // console.log("rewritten_gossip field:", resp?.rewritten_gossip)
      break
    }

    
    return gossip
  }

  async *propagate(seedGossips: Gossip[], injectedContext: Message[] = []): AsyncGenerator<Gossip>{
    const allGossips: Gossip[] = [...seedGossips];
    let currentGossips = seedGossips

    const seedPersonaIds = seedGossips.map(g => g.personaId);

    const order = this.getPropagationOrder(seedPersonaIds);
    const maxHops: number = this.config.maxHops ?? this.personas.length
    let hops: number = 0
    for (const edge of order) {
      if (hops > maxHops) break
      const persona = this.getPersonaById(edge.to);
      if (!persona) continue
      hops += 1
      const transformed: Gossip = await this.transformGossip(persona, currentGossips, injectedContext);
      allGossips.push(transformed);
      currentGossips = [transformed]
      yield transformed
    }
  }

  async getSummary(messages: Message[], persona: Persona, includeSystemPrompts: boolean = false, injectedContext: Message[] = []) {
    const personaSysPrompt = formatPersonaBasePrompt(persona)
    
    let instructionPrompt = `Review the conversation above and distill what happened.\n`;
    instructionPrompt += `Extract the key facts, actions, statements, conflicts, outcomes.\n\n`;

    // filter out any system prompts
    if (!includeSystemPrompts) {
      messages = messages.filter(m => m.role !== "system");
    }

    const msgHistory: Message[] = [
      {role: "system", content: personaSysPrompt},
      ...messages,
      ...injectedContext,
      {role: "user", content: formatPersonaGossipExtension(persona) + "\n\n" + GOSSIP_INSTRUCTION},
      {role: "user", content: instructionPrompt},
    ]

    const gossip: Gossip = {
      id: crypto.randomUUID(),
      content: "",
      personaId: persona.id,
      timestamp: Date.now(),
    }

    let retry: number = 0
    while (retry < this.config.maxRetries) {
      retry++;
      const resp = await generateToolCallResponse(this.config.modelName, msgHistory, formatTool)
      gossip.content = resp.rewritten_gossip
      gossip.belief = resp.belief
      gossip.reason = resp.reason
      // TODO: Validate response and if bad, retry.
      //       - Response lenght
      //       - Response quality???
      break
    }
    return gossip
  }

  /**
   * 
   * @param seedPersonaIds Ids of the root gossip holders of the gossip source.
   * @returns 
   */
  private getPropagationOrder(seedPersonaIds: string[]): GossipEdge[] {
    if (seedPersonaIds.length === 0) throw Error("GossipEngine: no seedPersonaIds provided")

    const visited = new Set<string>(seedPersonaIds)
    const unvisited = new Set<string>(this.personas.map(p => p.id))
    seedPersonaIds.forEach(id => unvisited.delete(id))

    // static/fixed relations from constructor edges
    const order: GossipEdge[] = [...this.staticEdges]
    order.forEach(e => {
      if (this.getPersonaById(e.from)) {
        visited.add(e.from)
        unvisited.delete(e.from)
      }
    })

    // dynamic relations for remaining unvisited personas
    while (unvisited.size > 0) {
      const targetId = [...unvisited][Math.floor(Math.random() * unvisited.size)]
      const sourceId = [...visited][Math.floor(Math.random() * visited.size)]

      order.push({
        from: sourceId,
        to: targetId,
        relation: "default",
      })

      visited.add(targetId)
      unvisited.delete(targetId)
    }

    return order;
  }

  getPersonaById(id: string): Persona | undefined {
    return this.personas.find(p => p.id === id);
  }
}
