import { formatPersonaBasePrompt, formatPersonaGossipExtension } from "../utils/promptFormatter.ts";
import { Gossip, GossipEdge, GossipEngineConfig, Persona } from "./types.ts";
import { generateStructuredChatResponse, generateToolCallResponse } from "../utils/ollamaHelpers.ts";
import { Message } from "../dialogManager/types.ts";
import { Tool } from "ollama";

// structured JSON format
const formatJson = {
  "type": "object",
  "properties": {
    "belief": {"type": "boolean", "description": "After interpreting the gossip through your character's perspective: do you ACCEPT that this event (or its essence) is justified, clever, or aligned with your values? Set false if it violates your core principles, even if you retell it dramatically."},
    "reason": {"type": "string", "description": "A very short description of MAXIMUM TWO SENTENCES explaining why you accepted or rejected the gossip."},
    "rewritten_gossip": {"type": "string", "description": "Rewritten gossip in your voice. As if you are telling someone else. CONFIDENTLY state it as truth. Frame it to match your perspective."},
  },
  "required": ["belief", "reason", "rewritten_gossip"]
}

const formatTool: Tool = {
      "type": "function",
      "function": {
        "name": "evaluate_persona_belief",
        "description": "Evaluates a conversation event based on the persona's specific moral framework and perspective.",
        "parameters": {
          "type": "object",
          "properties": {
            "belief": {
              "type": "boolean",
              "description": "Based on your persona's moral framework: do you judge the core event as ethically acceptable or justified? False if you consider it wrong, harmful, or unacceptable, even if entertaining."
            },
            "reason": {
              "type": "string",
              "description": "A very short and minimal description of MAXIMUM TWO SENTENCES based on your beliefs explaining why you accepted or rejected the conversation."
            },
            "rewritten_gossip": {
              "type": "string",
              "description": "Rewritten summary of the conversation in your voice. As if you are telling someone else. CONFIDENTLY state it as truth. Frame it to match your perspective."
            }
          },
          "required": ["belief", "explanation", "personal_summary"],
        }
      }
}

export class GossipEngine {
  config: GossipEngineConfig;
  staticEdges: GossipEdge[];

  constructor(public personas: Persona[], config: GossipEngineConfig, staticEdges: GossipEdge[] = []) {
    this.config = config;
    this.staticEdges = staticEdges;
  }

  /**
   * Get the config file with the expected behavior of some functions
   * EG. maxHops will represent the maximum amount of new gossip entries generated by getPropagationOrder()
   */
  getConfig(): GossipEngineConfig {
    const config: GossipEngineConfig = structuredClone(this.config)
    config.maxHops = config.maxHops ?? this.personas.length
    return config
  }

  /**
   * transform gossip trough a persona's perspective.
   */
  async transformGossip(persona: Persona, sourceGossips: Gossip[]): Promise<Gossip> {
    const personaSysPrompt = formatPersonaBasePrompt(persona) + "\n\n---\n\n" + formatPersonaGossipExtension(persona)
    
    let instructionPrompt = `You are ${persona.name}. You've heard these rumors circulating.\n`;
    instructionPrompt += `Some of these rumors might be wrong, exaggerated, or noisy. Filter them through your perspective.\n\n`;

    instructionPrompt += `Focus on the core event: who did what, and what happened.\n`;

    instructionPrompt += `\nRETELL IT YOUR WAY:\n`;
    instructionPrompt += `- Sound like yourself. Your speech style, your flair, your drama.\n`;
    instructionPrompt += `- Keep the skeleton of the story intact. The meat on those bones is yours to season.\n`;
    instructionPrompt += `- Your rewriting_mandate and examples show the style to follow.\n`;

    instructionPrompt += `\nABOUT BELIEF:\n`;
    instructionPrompt += `- Your persona's belief_rule decides if you believe the core event.\n`;
    instructionPrompt += `- If the core event violates your persona's values or goals, belief = false.\n`;

    instructionPrompt += `\nSPEAK WITH CONVICTION:\n`;
    instructionPrompt += `- Tell ONE version confidently. No hedging or multiple options.\n`;
    instructionPrompt += `- Speak with confidence (or doubt) based on who you are.\n`;
    instructionPrompt += `\n`


    // loop over all gossip and construct instruction prompt
    instructionPrompt += `Rumors you have heared:\n`
    sourceGossips.forEach((gossip, index) => {
      const author = this.personas.find((e) => gossip.parentId == e.id) || "an unkown source\n"
      instructionPrompt += `${index+1}. From ${author}:\n${gossip.content}\n\n`
    });
    
    instructionPrompt += `Now retell the story in your own words, as if you are telling the next person.\n`
    instructionPrompt += `Respond STRICTLY in this JSON format. Do not include lists, labels, or option names.\n`;

    const msgHistory = [
      {role: "system", "content": personaSysPrompt},
      {role: "user", "content": instructionPrompt},
    ]

    const gossip: Gossip = {
      id: crypto.randomUUID(),
      content: "",
      belief: false,
      personaId: persona.id,
      parentId: sourceGossips[0].id,
      timestamp: Date.now(),
    }

    let retry: number = 0;
    while (retry < this.config.maxRetries) {
      retry++;
      // const resp = await generateStructuredChatResponse(this.config.modelName, msgHistory, formatJson)
      const resp = await generateToolCallResponse(this.config.modelName, msgHistory, formatTool)
      console.log(typeof resp)
      console.log("generated gossip::", resp)

      if (!resp?.rewritten_gossip?.trim()) {
        console.warn(`transformGossip: empty content on attempt ${retry}, retrying...`)
        continue
      }

      gossip.content = resp.rewritten_gossip
      gossip.belief = resp.belief
      gossip.reason = resp.reason
      // TODO: Validate response and if bad, retry.
      //       - Response lenght
      //       - Response quality???

      // console.log("generated gossip::", resp)
      // console.log("rewritten_gossip field:", resp?.rewritten_gossip)
      break
    }

    
    return gossip
  }

  async *propagate(seedGossips: Gossip[]): AsyncGenerator<Gossip>{
    const allGossips: Gossip[] = [...seedGossips];
    let currentGossips = seedGossips

    const seedPersonaIds = seedGossips.map(g => g.personaId);

    const order = this.getPropagationOrder(seedPersonaIds);
    const maxHops: number = this.config.maxHops ?? this.personas.length
    let hops: number = 0
    for (const edge of order) {
      if (hops > maxHops) break
      const persona = this.getPersonaById(edge.to);
      if (!persona) continue
      hops += 1
      const transformed: Gossip = await this.transformGossip(persona, currentGossips);
      allGossips.push(transformed);
      currentGossips = [transformed]
      yield transformed
    }
  }

  async getSummary(messages: Message[], persona: Persona) {
    const personaSysPrompt = formatPersonaBasePrompt(persona) + "\n\n---\n\n" + formatPersonaGossipExtension(persona)
    
    const instructionPrompt = `
Interpret the conversation through your persona's worldview, values, and perspective.
Use all messages to form your take. Base your output on the conversation as seen through your character.

Focus on what actually happened:
- actions
- statements
- conflicts
- outcomes

Then respond using the tool:
- Decide whether you ACCEPT or REJECT the essence of what happened.
  Apply your persona's moral code, goals, and values. If it violates them, "belief" MUST be false.
- Explain your decision in AT MOST two short sentences.
- Rewrite the conversation confidently in your voice, framing events to support your perspective.
Preserve key details and context, but frame them to support your view.

Rules:
- Do NOT describe yourself or mention being an AI.
- Do NOT reference the original speakers directly unless it fits your narrative voice.
- If the core event violates your persona's moral code, functional goals, or values, belief = false.
- Be concise but expressive.
- Output strictly valid JSON matching the provided schema.
`;

    const msgHistory = [
      {role: "system", "content": personaSysPrompt},
      ...messages,
      {role: "user", "content": instructionPrompt},
    ]

    const gossip: Gossip = {
      id: crypto.randomUUID(),
      content: "",
      personaId: persona.id,
      timestamp: Date.now(),
    }

    let retry: number = 0
    while (retry < this.config.maxRetries) {
      retry++;
      const resp = await generateToolCallResponse(this.config.modelName, msgHistory, formatTool)
      gossip.content = resp.rewritten_gossip
      gossip.belief = resp.belief
      gossip.reason = resp.reason
      // TODO: Validate response and if bad, retry.
      //       - Response lenght
      //       - Response quality???
      break
    }
    return gossip
  }

  /**
   * 
   * @param seedPersonaIds Ids of the root gossip holders of the gossip source.
   * @returns 
   */
  private getPropagationOrder(seedPersonaIds: string[]): GossipEdge[] {
    if (seedPersonaIds.length === 0) throw Error("GossipEngine: no seedPersonaIds provided")

    const visited = new Set<string>(seedPersonaIds)
    const unvisited = new Set<string>(this.personas.map(p => p.id))
    seedPersonaIds.forEach(id => unvisited.delete(id))

    // static/fixed relations from constructor edges
    const order: GossipEdge[] = [...this.staticEdges]
    order.forEach(e => {
      if (this.getPersonaById(e.from)) {
        visited.add(e.from)
        unvisited.delete(e.from)
      }
    })

    // dynamic relations for remaining unvisited personas
    while (unvisited.size > 0) {
      const targetId = [...unvisited][Math.floor(Math.random() * unvisited.size)]
      const sourceId = [...visited][Math.floor(Math.random() * visited.size)]

      order.push({
        from: sourceId,
        to: targetId,
        relation: "default",
      })

      visited.add(targetId)
      unvisited.delete(targetId)
    }

    return order;
  }

  getPersonaById(id: string): Persona | undefined {
    return this.personas.find(p => p.id === id);
  }
}
